### ISSUE TITLE
电脑端网页CPU占用过高

### ISSUE THREAD

**Issue by cenaia** [LiWeny16/MarkdownOnline#2]
电脑端网页CPU占用过高
Chrome，edge，Firefox已测试，均CPU占用过高
配置：i5-6300HQ

**Comment by LiWeny16** [comment]
> 电脑端网页CPU占用过高 Chrome，edge，Firefox已测试，均CPU占用过高 配置：i5-6300HQ

已知这个问题，正在努力修复中
